# -*- coding: utf-8 -*

from pynsim import Engine
import pandas as pd
import shutil as sh

class ResInflows(Engine):
    """ This engine reads in inflows to all reservoirs. In this (simple) version, the engine reads the inflows into
    the 'surf_inflow' attribute for the Reservoir nodes. This is first engine to be run, in each time step.  T
    This is one of two places where the interaction with the hydrologic model happens (the other one is at the end of a timestep.
    Currently, I've only designed synthetic data for inflows into reservoirs. But this can also be extended to include
    inflows into junction points at various points across the watershed. Where the inflows should enter the system will
    be determined by the hydrologic modeler (i.e. Mikhail at IIASA)
    """
    name = "Engine to read inflows to all reservoirs generated by hydrol model"
    def run(self):

        ### THIS IS JUST TO CREATE THE HYPOTHETICAL INFLOW FILE THAT WILL BE CREATED BY IIASA'S HYDROL. MODEL
        t_in = 'data\inflow_' + str(self.target.network.current_timestep_idx) + '.txt'
        sh.copyfile(t_in, 'data\inflow.txt')

        hydinflows = pd.read_csv("data\inflow.txt", sep=" ")
        for res in self.target.nodes:
            if sum(hydinflows['Res_ID'] == res.name) == 1:
                res.surf_inflow = hydinflows[hydinflows['Res_ID'] == res.name].values.tolist()[0][1]
